/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "secondary-container": "#316bf3",
              "navy-dark": "#0F1B2D",
              "surface-container": "#eceef0",
              "text-primary": "#17202A",
              "on-tertiary-fixed-variant": "#00504d",
              "secondary-fixed": "#dbe1ff",
              "surface-variant": "#e0e3e5",
              "on-tertiary": "#ffffff",
              "inverse-primary": "#b7c7e5",
              "error": "#ba1a1a",
              "primary-fixed": "#d5e3ff",
              "on-error-container": "#93000a",
              "surface-container-high": "#e6e8ea",
              "primary-container": "#16263d",
              "on-surface-variant": "#44474d",
              "background": "#f8f9fb",
              "surface-container-highest": "#e0e3e5",
              "secondary-fixed-dim": "#b4c5ff",
              "surface-container-low": "#f2f4f6",
              "inverse-surface": "#2d3133",
              "on-secondary-fixed": "#00174b",
              "on-primary-fixed": "#0b1c32",
              "secondary": "#0051d5",
              "tertiary-container": "#002b29",
              "on-secondary-container": "#fefcff",
              "primary": "#011127",
              "border-base": "#D9E0E7",
              "error-container": "#ffdad6",
              "surface-dim": "#d8dadc",
              "on-background": "#191c1e",
              "on-secondary": "#ffffff",
              "success": "#10B981",
              "text-secondary": "#5E6875",
              "on-surface": "#191c1e",
              "warning": "#F59E0B",
              "tertiary-fixed": "#7ef5ef",
              "tertiary-fixed-dim": "#60d9d3",
              "surface-bright": "#f8f9fb",
              "on-primary": "#ffffff",
              "tertiary": "#001413",
              "teal-dark": "#0E7F7B",
              "action-blue-dark": "#1D4ED8",
              "surface": "#FFFFFF",
              "surface-tint": "#505f79",
              "on-tertiary-fixed": "#00201f",
              "primary-fixed-dim": "#b7c7e5",
              "on-primary-container": "#7e8da9",
              "text-muted": "#87919D",
              "info": "#3B82F6",
              "on-error": "#ffffff",
              "outline-variant": "#c5c6ce",
              "critical": "#EF4444",
              "on-secondary-fixed-variant": "#003ea8",
              "surface-secondary": "#F1F4F7",
              "action-blue-light": "#EFF6FF",
              "on-primary-fixed-variant": "#384760",
              "inverse-on-surface": "#eff1f3",
              "on-tertiary-container": "#009d98",
              "surface-container-lowest": "#ffffff",
              "outline": "#75777e",
              "brand-blue": "#2563EB"
          },
          "borderRadius": {
              "DEFAULT": "0.5rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "0.75rem"
          },
          "spacing": {
              "page-padding": "32px",
              "sidebar-width": "240px",
              "component-gap": "24px",
              "gutter": "16px",
              "base": "8px",
              "compact-padding": "12px"
          },
          "fontFamily": {
              "section-title": ["Hanken Grotesk"],
              "kpi-primary": ["Hanken Grotesk"],
              "caption": ["Inter"],
              "page-title": ["Hanken Grotesk"],
              "label-sm": ["Inter"],
              "body-table-bold": ["Inter"],
              "data-tabular": ["Inter"],
              "body-table": ["Inter"]
          },
          "fontSize": {
              "section-title": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
              "kpi-primary": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "caption": ["11px", { "lineHeight": "14px", "fontWeight": "400" }],
              "page-title": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
              "body-table-bold": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
              "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
              "body-table": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
          }
      }
  },
  plugins: [],
}
